### PR TITLE
Add load balancer pool and member provisioning status (#108)

### LINKED ISSUE #108: expose LB pool and LB pool member provisioning statuses
## What

Would love hear your thoughts about exposing something like:
- `loadbalancer_pool_provisioning_status`
- `loadbalancer_pool_member_provisioning_status`

## Why

So it's possible to be alerted on errors provisioning LB pools and their members.

## How

For example, there seems to be such attributes available in Gophercloud:

>```golang
>// The provisioning status of the pool.
>// This value is ACTIVE, PENDING_* or ERROR.
>ProvisioningStatus string `json:"provisioning_status"`
>```

...on both:
- Pool: \
https://github.com/gophercloud/gophercloud/blob/0ffab06fc18e06ed9544fe10b385f0a59492fdb5/openstack/loadbalancer/v2/pools/results.go#L99-L101
- Pool member: \
https://github.com/gophercloud/gophercloud/blob/0ffab06fc18e06ed9544fe10b385f0a59492fdb5/openstack/loadbalancer/v2/pools/results.go#L214-L216

I'm not sure about how to implement this yet. A first thought could be by extending the loadbalancer file, i.e. here:
https://github.com/mercedes-benz/kosmoo/blob/72c46a7fe4a73939d0fbfddc3d2366497f44b872/pkg/metrics/loadbalancer.go#L42-L44

### PR DESCRIPTION
**Pull request by oscr**
This pr implements
* `loadbalancer_pool_provisioning_status`
* `loadbalancer_pool_member_provisioning_status`

Fixes #108

### CODE REVIEW

**Comment by oscr** [comment]
Looking for general feedback if this is an acceptable solution. 

Work still left: 
* Generate `metrics.md` 
* Verify with OpenStack at work

**Comment by MPV** [comment]
Curious about your thoughts here @seanschneeweiss <3 

@oscr: 👏

**Comment by oscr** [comment]
Minor draft update that ensures pool and members are populated.

```shell
 curl 127.0.0.1:9183/metrics 2>/dev/null| grep -E -e '^#.*kos' | grep loadbala

# HELP kos_loadbalancer_admin_state_up Load balancer admin state up
# TYPE kos_loadbalancer_admin_state_up gauge
# HELP kos_loadbalancer_pool_member_provisioning_status Load balancer pool member provisioning status
# TYPE kos_loadbalancer_pool_member_provisioning_status gauge
# HELP kos_loadbalancer_pool_provisioning_status Load balancer pool provisioning status
# TYPE kos_loadbalancer_pool_provisioning_status gauge
# HELP kos_loadbalancer_provisioning_status Load balancer status
# TYPE kos_loadbalancer_provisioning_status gauge
```

**Review by tobiasgiese — APPROVED** [review]
Sorry for the late reply @oscr.
I like the idea, thanks for the implementation! 🙂

**Comment by oscr** [comment]
Thank you for the review and accepting the @tobiasgiese! Are there any plans for a new release so we can get the latest changes into production?

**Comment by tobiasgiese** [comment]
@oscr we'll take a look next week and do a next release 🙂

cc @seanschneeweiss / @johannesfrey just for a reminder

**Comment by oscr** [comment]
That would be perfect. Thank you for your help @tobiasgiese :pray:

**Pull request merged**
