### PR TITLE
Add info logging if no loadbalancers are found

### PR DESCRIPTION
**Pull request by oscr**
When working on #111 I didn't get the expected load balancer metrics. 

```
# HELP kos_loadbalancer_admin_state_up Load balancer admin state up
# TYPE kos_loadbalancer_admin_state_up gauge
# HELP kos_loadbalancer_provisioning_status Load balancer status
# TYPE kos_loadbalancer_provisioning_status gauge
```

After some investigation I noticed that the test project didn't actually have any load balancers in it and therefore no metrics where published. By adding this info log I hope that others might find this mistake faster than I did :sweat_smile:

### CODE REVIEW

**Comment by seanschneeweiss** [comment]
Thank you very much for the pull request.

**Comment by seanschneeweiss** [comment]
To merge this Pull Request we require a signed CLA.
Is this something that you could do? That would be great. Thanks a lot and sorry for the process.

> Please sign the Mercedes-Benz Tech Innovation CLA "[2022-04-25_MB_FOSS_CLA_MBTI.pdf](https://github.com/mercedes-benz/foss/blob/master/cla/2022-04-25_MB_FOSS_CLA_MBTI.pdf)" and send a scan of the CLA to [CLA-mbti@mercedes-benz.com](mailto:CLA-mbti@mercedes-benz.com).

**Comment by oscr** [comment]
No problem! I will do it immediately.

**Comment by oscr** [comment]
@seanschneeweiss I have mailed a signed copy now.

**Comment by tobiasgiese** [comment]
> @seanschneeweiss I have mailed a signed copy now.

@oscr the signed CLA has been arrived! We can merge the PR now 🙂

**Comment by oscr** [comment]
Awesome! Thanks @tobiasgiese and @seanschneeweiss! :pray:

**Pull request merged**
